### ISSUE TITLE
有关CI自动构建的问题

### ISSUE THREAD

**Issue by 401U** [AnzhiZhang/ChatHub#11]
刚刚为仓库添加了CI构建脚本，将在推送tag时自动发release，同时编译插件加入release assets, 并自动生成变更日志（基于commit记录）

是否需要同时自动发布插件到 CurseForge/Modrinth平台（可通过 [mc-publish](https://github.com/Kir-Antipov/mc-publish) 实现）？这需要配置相应的环境变量，加入对应平台的口令，所以只有仓库主人能够操作

**Comment by AnzhiZhang** [comment]
可以做，可以告诉我变量名，我加到仓库变量中去

**Comment by 401U** [comment]
mc-publish的范例中使用的环境变量就`MODRINTH_TOKEN` 和  `CURSEFORGE_TOKEN` 两个，获取地址为： [curseforge](https://authors-old.curseforge.com/account/api-tokens)  和 [modrinth](https:modrinth.com/settings/account)

自行设置其他变量名也可，最终与action中的配置一致即可

**Comment by 401U** [comment]
更新了action, 等加入环境变量后，取消其中注释部分即可

另：此项目暂未在modrinth上发布，故modrinth的id部分需要等发布后进行修改

**Comment by AnzhiZhang** [comment]
morith 已经在审核了，id应该在哪填写？

**Comment by 401U** [comment]
> 两个secret 添加好了，morith 在审核了，id应该在哪填写？

.github/workflows/Release.yml 文件中，被注释的行里有`modrinth-id`

**Comment by AnzhiZhang** [comment]
已经修改好了
