### ISSUE TITLE
[bug]无法转发其他聊天频道的消息在minecraft

### ISSUE THREAD

**Issue by safesaffawa** [AnzhiZhang/ChatHub#12]
如图
![e544c4c1bb9b0fb8172f3821f6a2a7bf](https://github.com/AnzhiZhang/ChatHub/assets/125875649/fdc09034-d8d0-4ce2-85f1-cf4cc04286f2)

**Comment by AnzhiZhang** [comment]
只支持单一频道

**Comment by safesaffawa** [comment]
是这样的吗

**Comment by safesaffawa** [comment]
此问题可以关闭了 除非会有新的版本来支持

**Comment by AnzhiZhang** [comment]
> 此问题可以关闭了 除非会有新的版本来支持

本来设计的就是转发到一个频道，同理qq也是到一个群，没有支持多个频道/多个群的意义
