### ISSUE TITLE
希望支持api变量，以及变量的hex颜色

### ISSUE THREAD

**Issue by xiaoluofa** [AnzhiZhang/ChatHub#16]

**Comment by AnzhiZhang** [comment]
请详细说明api变量的含义，以及颜色的标准

**Comment by xiaoluofa** [comment]
> 请详细说明api变量的含义，以及颜色的标准

...我换trchat了，不过插件还是有点用的，就是一直报错。
velocity，玩家加入事件会报错，1.20.4
