### ISSUE TITLE
服务器名和玩家名可点击后，破坏了消息颜色的配置

### ISSUE THREAD

**Issue by AnzhiZhang** [AnzhiZhang/ChatHub#18]
![56A73Y(EXWJDM6AVLF1(8V_tmb](https://github.com/AnzhiZhang/ChatHub/assets/37402126/47a8690e-0494-48df-8bce-d672def8f1b6)
```text
[servername]
lobby='§8lobby'
survival='§2survival'

[minecraft.message]
chat = '§7[{plainServer}] {name}: {message}'
join = '§7{name}§7 joined {plainServer}'
leave = '§7{name}§7 left the server'
switch = '§7{name}§7 left {serverFrom}§7 and joined {serverTo}'
```

**Comment by AnzhiZhang** [comment]
See also: 0539a878e6b18dee3a2d0ebc4bed720d662c713d, 1802dc317e7b0101c4bd7e246b95d850f0abdc01

**Comment by AnzhiZhang** [comment]
修复方式：考虑删除可点击的玩家名和服务器名，通过配置文件推断颜色过于复杂。
@401U request review

**Comment by 401U** [comment]
可以先revert掉这两个改动，等有时间了我再看看能否让模板颜色和点击事件间无冲突

**Comment by AnzhiZhang** [comment]
尝试了一下，只要构建 Component 就会自带颜色
