### ISSUE TITLE
当velocity.toml配置文件中子服名字为中文时,[servername]设置失效

### ISSUE THREAD

**Issue by FnTlv** [AnzhiZhang/ChatHub#3]
"登录大区" = "§b§l登录区" 子服"登陆大区"设置名字为“§b§l登录区”.
此时{server}显示为"登陆大区"

**Comment by AnzhiZhang** [comment]
请尝试移除键的引号，若不行请使用英文。
中文可能造成不可预知的 Toml 库的意外情况，若坚持使用请到正常的仓库提问

**Comment by AnzhiZhang** [comment]
另外此处的键应当与 velocity 配置文件中的服务器名称对应，若无法找到将显示默认缺省值，即为 vc 配置文件中的服务器名称

**Comment by FnTlv** [comment]
删除键的引号会导致报错。加引号无报错，应该与velocity 配置文件中的服务器名称对应起来了，但是不知道为啥会显示键。

**Comment by AnzhiZhang** [comment]
显示为服务器名称**很可能**因为使用的不对应的配置，即擅自增加了引号。若移除后无效或报错，请自行学习 Toml 语法或找相关 API 库寻求帮助，恕无法提供帮助。建议使用英文
