### ISSUE TITLE
希望增加qq转发功能

### ISSUE THREAD

**Issue by addre98** [AnzhiZhang/ChatHub#5]

**Comment by addre98** [comment]
希望使用它来代替qq_api和qq_chat

**Comment by addre98** [comment]
希望它可以替代qq_api和qq_chat的简单功能

**Comment by AnzhiZhang** [comment]
> 希望它可以替代qq_api和qq_chat的简单功能

只会做消息转发，指令和白名单等功能没有计划，因为这是一个聊天插件

**Comment by safesaffawa** [comment]
我来问下 功能做了吗0.0

**Comment by AnzhiZhang** [comment]
> 我来问下 功能做了吗0.0

在计划中，开发有些困难，使用的 go-cqhttp 目前由于风控登录较为困难

**Comment by safesaffawa** [comment]
但是作者可以去看看koishi 
他们给的方案是 在qqnt上注入 自己的超时空猫猫
要是作者可以做一个koishi插件的话 那再好不过

**Comment by AnzhiZhang** [comment]
> 但是作者可以去看看koishi 他们给的方案是 在qqnt上注入 自己的超时空猫猫 要是作者可以做一个koishi插件的话 那再好不过

什么奇怪东西，没兴趣

**Comment by AnzhiZhang** [comment]
由于 QQ 官方机器人的发布，该功能的实现方式仍需进一步评估
